// Code generated by goctl. DO NOT EDIT.
package types

type GetUserReq struct {
	UserID int64 `path:"user_id"`
}

type GetUserRes struct {
	User   User   `json:"user"`
	Result Result `json:"result"`
}

type LoginReq struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type LoginRes struct {
	User   User   `json:"user"`
	Result Result `json:"result"`
}

type RegisterReq struct {
	Fullname string `form:"fullname"`
	Password string `form:"password"`
	Email    string `form:"email"`
}

type RegisterRes struct {
	User   User   `json:"user"`
	Result Result `json:"result"`
}

type Result struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID       int64  `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}
