version: '3.4'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cnpm
      MYSQL_USER: tholgbg
      MYSQL_PASSWORD: abcdef
    ports:
      - "3306:3306"
    networks:
      - db_network

  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - database
    networks:
      - db_network
  # frontend:
  #   image: frontend
  #   build: 
  #     context: ./frontend
  #     dockerfile: ./frontend/Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend

volumes:
  database:
    driver: local
networks:
  db_network:
    driver: bridge

